

import { Inter } from 'next/font/google';
import './globals.css';
import { StateContext } from '../context/StateContext';
import { LayOut } from '../components';
import { Toaster } from 'react-hot-toast';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
    return (
        <html lang="en">
        <body className={inter.className}>
        <StateContext> {/* Wrap with your context provider */}
            <LayOut> {/* Use your custom layout */}
                <Toaster /> {/* Include Toaster */}
                {children}
            </LayOut>
        </StateContext>
        </body>
        </html>
    );
}
